version: '3.8'

services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wiki-to-pdf-api
    volumes:
      - ./output:/app/output
    restart: always
    environment:
      - LOG_LEVEL=info
    networks:
      - gbr1
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: wiki_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - gbr1               
networks:
  gbr1:
    external: true      